### ISSUE TITLE
plot.xlsx and visit.xlsx styling needs to be fixed.

### ISSUE THREAD

**Issue by clarlars** [odk-x/tool-suite-X#71] opened 2018-06-06 20:07 UTC
#### Software and hardware versions 
Survey 2.0.5 and Android 6.0.1

#### Problem description
The styling for the plot.xlsx and visit.xlsx forms needs to be fixed to not use white text on white backgrounds.  

#### Steps to reproduce the problem
Open up plot.xlsx or visit.xlsx with the pre-populated data, the instances list shows up with white text in a white background.  

#### Expected behavior
User should be able to read all text.

**Comment by wbrunette** [comment] 2021-03-31 21:17
@tegajunior  here is a good first issue to get yourself familiar with setting up app-designer and using Survey. This is an older issue that could have been fixed so you should try to replicate the issue. The "New Date Prompts for ODK-X Survey" project will use app-designer and Survey so this is a good way to get setup and complete an issue at the same time.

References to get started

- https://docs.odk-x.org/basics-install/
- https://docs.odk-x.org/survey-sample-app/
- https://docs.odk-x.org/getting-started-2-architect/

If you are able to replicate the problem please submit a pull request to fix the issue.

**Comment by wbrunette** [comment] 2021-03-31 21:20
You should try to replicate this issue on the current release to see if it's still an issue. If not we can close the issue :)

**Comment by chinenyeokafor** [comment] 2021-04-09 17:31
@wbrunette Can I do this?

**Comment by wbrunette** [comment] 2021-04-09 17:33
@chinenyelilian I have assigned the issue to you. Note this is an older issue so someone might have fixed it but you should give it a try.

**Comment by chinenyeokafor** [comment] 2021-04-10 18:16
Thank you @wbrunette 
The error below comes up when I attempt to open a form.
![Screenshot_20210410-185827](https://user-images.githubusercontent.com/28391088/114280441-1cab5e80-9a31-11eb-969a-d90604b24d21.png)

**Comment by wbrunette** [comment] 2021-04-10 19:34
@chinenyelilian it's a good idea to search on the forum.odk-x.org with problems as people may have already had similar issues. My first guess at the issue is this one: https://forum.odk-x.org/t/err-connection-refused-problem-accesing-forms-with-survey/819

**Comment by chinenyeokafor** [comment] 2021-04-10 23:44
@wbrunette Thank you so much.
My mobile needed additional settings to access the form.
Apparently this issue have been resolved as I could read all text on the form. See sample photo.

![image](https://user-images.githubusercontent.com/28391088/114287420-9279ef00-9a5e-11eb-8c8f-189e9f92927f.png) 
![image](https://user-images.githubusercontent.com/28391088/114287461-dbca3e80-9a5e-11eb-91bd-88fabe113303.png)

**Comment by wbrunette** [comment] 2021-04-11 18:28
@chinenyelilian while looking at the summary data in ODK-X Tables is a big part of the application the issue talks about a form and the forms are rendered in ODK-X Survey. Please check the forms in the Survey application and let us know if the problem still exists.

**Comment by chinenyeokafor** [comment] 2021-04-11 19:01
@wbrunette 
I couldn't read any text on the plot form.

I have Survey 2.1.7 rev 240 and Android version 9.
![Screenshot_20210411-195220.png](https://user-images.githubusercontent.com/28391088/114317559-8113ff80-9abd-11eb-8aa2-94be3c2242a7.png)
![Screenshot_20210411-195256.png](https://user-images.githubusercontent.com/28391088/114317593-a9036300-9abd-11eb-804b-8502d8652e67.png)

**Comment by wbrunette** [comment] 2021-04-11 19:03
Well the issue still exists :) This needs to be fixed

**Comment by chinenyeokafor** [comment] 2021-04-11 19:19
Yes, I will work on it and raise a pull request.

**Comment by chinenyeokafor** [comment] 2021-04-13 15:06
Dear @wbrunette,

I have modified the code to fix this issue on my device . However I am having a challenge locating the repository of the form configuration on the server to effect the fix. 

Kindly assist

**Comment by wbrunette** [comment] 2021-04-13 16:26
@chinenyelilian you do not need to update the server. You can push updated files to your mobile device or Andriod emulator over USB.

Check out the following: https://docs.odk-x.org/getting-started-2-architect/

The forms are available in the Application Designer. Here is how to set it up https://docs.odk-x.org/app-designer-setup/

Also check out this documentation: https://docs.odk-x.org/build-app/

**Comment by chinenyeokafor** [comment] 2021-04-13 19:09
@wbrunette I have already moved the updated file to my mobile device. Opening the plot form with the survey application produces the expected result.
![Screenshot_20210413-195955.png](https://user-images.githubusercontent.com/28391088/114607133-ffed7180-9c50-11eb-9c1c-426727805523.png)

**Comment by chinenyeokafor** [comment] 2021-04-17 11:09
@wbrunette This is a reminder that you are yet to review the pull request I created for this issue. 

I have observed same issue with the v2.1.8 preview release.

**Closed** 2021-04-26 20:19 UTC
Labels: Application Designer, Low-Priority, Try To Replicate, easy win, good first issue
