### ISSUE TITLE
Feature Update: Warning on 'Accidental' Exit from Main Screen

### ISSUE THREAD

**Issue by VarunT11** [odk-x/tool-suite-X#202] opened 2021-03-15 03:39 UTC
**Current Scenario**:
- On clicking the back button from the Main-Screen of the ODK-Services Application, the Application gets exited immediately.

**Issue**:
- For better User Experience, a warning message should be provided to the User before leaving the Application by clicking on the Back Button.

**Proposed Solution**:
- Implementation of the above Issue by prompting a warning message when the User clicks on the Back Button. 
- The User would perform the required operation of remaining in the Application or Exiting it by interacting with the Warning Message.

**Reference**:
- The October 2019 Convening of Improving UX for Existing Users.
- https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit#

**PS**: If this Feature Update appears to be a valid one, I would like to work on it.

**Comment by IAmJaishree** [comment] 2021-03-15 07:57
Yes, I too think this will enhance the user experience. After clicking on the back button we can ask user to click back again to exit the app.

**Comment by VarunT11** [comment] 2021-03-15 08:05
@IAmJaishree Yeah Exactly!
Or we can just display a _Snackbar_ with a Message confirming whether the User wants to Leave the Application or not. If we implement it this way, then the _Snackbar_ would look like this in the Application:
![Screenshot_20210315-101011__01](https://user-images.githubusercontent.com/58032608/111121871-3624cc00-8593-11eb-84e3-db593d06c025.jpg)

**Comment by wbrunette** [comment] 2021-03-15 16:03
The issue is that Services is called from ODK-X Tables and ODK-X Survey. The 3 work together so it appears seamless to move between the applications. Therefore it will be akward for the user to have to confirm exit when they did not even realize they switched from Tables to Services (or Survey to Services).

**Comment by VarunT11** [comment] 2021-03-15 17:43
@wbrunette Yes I agree that would be awkward, but this feature would be implemented only on the _**MainActivity**_ of Services Application and that too on Pressing the Back Button. Thus it would have no effect on the Current Flow between the 3 Applications.

**Comment by wbrunette** [comment] 2021-03-15 17:51
@VarunT11 I agree that only on MainActivity could solve the problem, as long as there are can bring this up for discussion. I am slightly worried about the snackbar as that people will miss the message at the bottom and be frustrated. I think this needs a discussion with the PMC/TSC. I am happy to bring it up at the next meeting. You can start to implement it if you want, but changes may come from the committee.

**Comment by VarunT11** [comment] 2021-03-15 18:08
@wbrunette Regarding the Snackbar, we can decide a convenient time duration between 2 to 4 seconds of displaying the Snackbar such that a User gets sufficient time to read the warning message and then perform the next operation accordingly.
Also we can extend this feature of prompting a warning message on pressing the Back Button to the Survey and the Table Apps as well.

**Comment by wbrunette** [comment] 2021-03-16 17:07
@VarunT11 We discussed this at the PMC/TSC meeting. The notes from the October 2019 Convening of Improving UX for Existing Users, about warning for exit was actually for tables.

We encourage you to take on the issue from the convening

Duplicate of https://github.com/odk-x/tool-suite-X/issues/129

**Closed** 2021-03-16 17:07 UTC
