### ISSUE TITLE
Add a last synced time and date 

### ISSUE THREAD

**Issue by elmps2018** [odk-x/tool-suite-X#107] opened 2019-07-28 22:24 UTC
There doesn't seem to be any way to tell, in ODK services, when I last synced. This would be a very helpful item to display on the syncing screen so that if, say, you are an enumerator and the field supervisor emails to say "I added new observations at 9am yesterday, please make sure you have synced" you can just pop open the syncing screen and see whether or not you've synced since 9am yesterday. Supervisors could also pop open fieldworkers tablets to make sure everything has synced at the end of day. I am guessing this info already exists somewhere inside Services, so hopefully this would be easy to display!
+1 vote in features on ODK Forum as of July 28 2019: https://forum.opendatakit.org/t/add-a-last-synced-time-and-date-to-odk-services/12756

**Comment by IAmJaishree** [comment] 2021-03-13 07:36
this seems same as #155 to me, if not can I get some more info on this?

**Comment by linl33** [comment] 2021-03-13 15:18
Yes, it's a duplicate of #155. @IAmJaishree thanks for reporting this.

**Closed by linl33** 2021-03-13 15:18 UTC
Labels: Medium-Priority, Services, enhancement
