### ISSUE TITLE
Improve UX when synching and showing filepaths

### ISSUE THREAD

**Issue by jbeorse** [odk-x/tool-suite-X#131] opened 2019-12-03 11:38 UTC
Writing the filepath names when synching
- Unpleasant flickering 
- Show a sync progress bar or similar instead 

From the 2019 convening: https://docs.google.com/document/d/1_4x9x3eHxo4qevBRlpmCC9L2bVlUkAQuAlidT8wJDzI/edit#

**Comment by VarunT11** [comment] 2021-03-13 17:48
@jbeorse I would like to work on this Issue. Please assign it to me!

**Comment by jbeorse** [comment] 2021-03-13 22:18
Sure thing @VarunT11.  Are you thinking of participating in Google Summer of Code? Here is a link to our main forum post that should help you get started: https://forum.odk-x.org/t/welcome-gsoc-applicants/1195

**Comment by VarunT11** [comment] 2021-03-16 15:51
**Current Scenario**:
- During Sync of the Application with the Server, a _ProgressDialog_ is displayed which shows the current status of Sync.
![Screenshot_20210315-003041__01](https://user-images.githubusercontent.com/58032608/111338379-e6cac280-869c-11eb-8074-cdf654d9ebcc.jpg)

**Issues**:
- _ProgressDialog_ Class was deprecated in API Level 26 
(Source : https://developer.android.com/reference/android/app/ProgressDialog)
- The Progress Dialog did not display the current Progress of the Sync and just showed a spinner.

**Proposal**:
- Implementation of the Progress Bar (https://developer.android.com/reference/android/widget/ProgressBar) instead of the Progress Dialog in the Application.

**PS**: @jbeorse @linl33 @wbrunette Please take a look at the above proposal and suggest if I should work on it or not!

**Comment by riturajjain2000** [comment] 2021-03-16 16:05
If you are working on it the Progress bar then using Progress indicators in place of ProgressBar is better as it is a Material Component, for details see - https://material.io/components/progress-indicators/android#using-progress-indicators

Though it looks the same as a Progress Bar, still using Material Components is a better practice

**Comment by wbrunette** [comment] 2021-03-16 16:28
@VarunT11 one issue with a progress bar is you will be unaware of how many total steps are needed in the syncing process. We definitely need to move to a newer UI widget and replace the ProgressDialog. The issue is assigned to you to work on currently.

**Comment by linl33** [comment] 2021-03-30 06:18
@wbrunette @jbeorse With the updated progress bar do you think we can close this issue?

**Closed** 2021-03-30 08:45 UTC
Labels: Low-Priority, Requires Specification, Services, convening-2019-ux-improvements, enhancement
