### ISSUE TITLE
Document the logging capabilities of apps

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#81] opened 2019-04-09 15:42 UTC

**Comment by amarealcoder** [comment] 2021-03-31 03:49
Hi mentors, Please can you assign this task to me.

**Comment by wbrunette** [comment] 2021-03-31 05:22
@amarealcoder I have assigned the issue to you.

**Comment by amarealcoder** [comment] 2021-04-05 16:27
Hi @ wbrunette <https://app.slack.com/team/U01PXFW021Z>    I have
successfully finished the docker build. Please, do you mind updating me
with what next step I need to take? The task I was assigned, how do I go
about it?

**Comment by wbrunette** [comment] 2021-04-05 20:21
@amarealcoder this is not well document, which is why this issue exists, so someone can come up with a set of instructions.

To get you started I have put links to the 3 types of logging that exist and some pointers to get you started.

ODK-X Logging System
-------------------------------
ODK-X log files are stored in the /opendatakit/<appname>/output/ directory see:  https://docs.odk-x.org/config-file-structure/
Also see: https://forum.odk-x.org/t/wrong-metadata-writed-survey-write-local-language-es-rather-than-es-es-why/1157
https://www.youtube.com/watch?v=jzqu7w4VepM
https://forum.odk-x.org/t/missing-data-error-when-downloading-forms-error-de-datos-faltantes-al-descargar-formularios/311/3

Android Logging
--------------------------
The Android logging system provides a mechanism for collecting and viewing system debug output. Logs from various applications and portions of the system are collected in a series of circular buffers, which then can be viewed and filtered by the logcat command. You can use logcat from an ADB shell to view the log messages. You can also see it Android Studio.
https://developer.android.com/studio/command-line/logcat#:~:text=Logcat%20is%20a%20command-line%20tool%20that%20dumps%20a,messages%20from%20the%20Logcat%20window%20in%20Android%20Studio.
https://www.brainbell.com/android/logcat.html

Sync-Endpoint Docker
------------------------------
https://forum.odk-x.org/t/odk-x-digitalocean-ldap-service-is-not-running/605
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by amarealcoder** [comment] 2021-04-06 06:53
Thanks for the documents. I have gone through them yet nothing is making
sense to me. Is it possible that you assign a more basic issue I can work
on as a beginner...I really want to get a hang of this. I am still
floating. Or if this one is quite basic for a beginner, how do I get to
understand it better. I hope you don't mind me bugging you all these while.

**Comment by amarealcoder** [comment] 2021-04-06 08:09
Does this "document the logging capabilities of apps" file already exist in
the repository because I cannot find the file or am I meant to build the
documentation from scratch?

**Comment by wbrunette** [comment] 2021-04-06 15:49
@amarealcoder you are correct there is no document so this is a start from scratch issue. This might be an easier documentation issue: https://github.com/odk-x/tool-suite-X/issues/138

**Comment by iamhks** [comment] 2021-04-07 13:42
@wbrunette If Miracle is going to opt for some other issue. I would like to try this one. Also, by "apps" I guess this means for the 3 apps we have-survey,services and tables or if I am wrong please clarify.

And, Hi @amarealcoder Even I was overwhelmed initially but I started with reading the docs first and then fixing typos, and making videos for example here: https://github.com/odk-x/tool-suite-X/issues/239 
Unfortunately, all the video issues have been assigned, but if you want to get started I have one more assigned to me, you can take over here: https://github.com/odk-x/tool-suite-X/issues/241

**Comment by wbrunette** [comment] 2021-04-13 16:50
@amarealcoder can you give us an update on the issue? Do you have any questions? It is fine to find a different issue if you don't want to work on this one, but please let us know so we can remove you from being assigned.

**Comment by amarealcoder** [comment] 2021-04-13 16:58
I am sorry I have not been able to give update on the issue due to
circumstances beyond my control. You can go ahead and assign someone else.
Thanks.

On Apr 13, 2021 5:50 PM, "wbrunette" ***@***.***> wrote:

@amarealcoder <https://github.com/amarealcoder> can you give us an update
on the issue? Do you have any questions? It is fine to find a different
issue if you don't want to work on this one, but please let us know so we
can remove you from being assigned.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/odk-x/tool-suite-X/issues/81#issuecomment-818887663>,
or unsubscribe

**Comment by wbrunette** [comment] 2021-04-13 16:59
@amarealcoder you can keep the issue if you want until you have time. I was simply checking in.

**Comment by amarealcoder** [comment] 2021-04-13 17:02
No, its ok. I will pick some other issue when I resume.

**Comment by wbrunette** [comment] 2021-04-13 17:03
@iamhks are you still interested in this issue?

**Comment by iamhks** [comment] 2021-04-13 17:55
@wbrunette Yes, please assign it to me.

**Comment by wbrunette** [comment] 2021-04-13 18:01
@iamhks I have assigned the issue to you.

**Comment by iamhks** [comment] 2021-04-26 19:33
> @wbrunette Also, by "apps" I guess this means for the 3 apps we have-survey,services and tables or if I am wrong please clarify.

@wbrunette Could you shed some light into this? Also am I supposed to document for all the 3 logging Systems or just the ODK-X one would suffice?

**Comment by wbrunette** [comment] 2021-04-26 19:39
@iamhks The issue is for all 3 types of logging systems. We can break the issue up if you do not feel comfortable documenting all 3 systems. https://github.com/odk-x/tool-suite-X/issues/81#issuecomment-813627457

**Closed** 2021-05-08 23:13 UTC
Labels: Documentation, Medium-Priority, easy win, good first issue
