### ISSUE TITLE
Wrong link in Services preferences

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#203] opened 2021-03-15 05:51 UTC
There is a link in the preferences for Services that points to [http://opendatatkit.org](http://opendatatkit.org). The link should point to [https://docs.odk-x.org](https://docs.odk-x.org) instead.

**Comment by IAmJaishree** [comment] 2021-03-15 06:04
@linl33 can I work on it?

**Comment by linl33** [comment] 2021-03-15 06:54
Sure, you may go ahead. Thanks.

**Comment by 96RadhikaJadhav** [comment] 2021-03-15 18:44
@linl33 Is this issue resolved or still open? If open can I work on it?

**Comment by wbrunette** [comment] 2021-03-15 18:45
@96RadhikaJadhav the issue is currently assigned to @IAmJaishree to complete.

**Closed** 2021-03-16 20:25 UTC
Labels: Services, bug, easy win, good first issue
