### ISSUE TITLE
Crash in LoginActivity in Services

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#222] opened 2021-03-30 04:59 UTC
LoginActivity crashes if screen is rotated on the about screen.

## Steps to reproduce
1. Open Services
2. Click Change User/Logout
3. Click About
4. Rotate screen
5. Click back
6. Crash

## Stacktrace
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.opendatakit.properties.PropertiesSingleton.getProperty(java.lang.String)' on a null object reference
        at org.opendatakit.services.sync.actions.activities.LoginActivity.onBackPressed(LoginActivity.java:90)
        at android.app.Activity.onKeyUp(Activity.java:2980)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2715)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:354)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4733)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4605)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4326)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4487)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by VarunT11** [comment] 2021-03-30 05:17
@linl33 Can I look into this?

**Comment by linl33** [comment] 2021-03-30 06:09
@VarunT11 Please finish the 2 other issues assigned to you first. We try to make sure people don't work on too many issues at the same time so there are enough to go around.

**Comment by pawanharariya** [comment] 2021-03-30 06:49
@linl33 Can I work on this?

**Comment by riturajjain2000** [comment] 2021-03-30 08:31
Can I work on this ?

**Comment by pawanharariya** [comment] 2021-03-30 10:22
@linl33 https://github.com/odk-x/services/blob/c10f7182771aa98482496048f592d95b24a99f13/services_app/src/main/java/org/opendatakit/services/sync/actions/activities/LoginActivity.java#L88-L90

@Override
   public void onBackPressed() {
      String authType = mProps.getProperty(CommonToolProperties.KEY_AUTHENTICATION_TYPE);

here mProps are not initialized after activity recreation, calling getProps() method of parent class solves the problem.

**Comment by linl33** [comment] 2021-03-31 02:30
@riturajjain2000 I've assigned this issue to you. Thanks.

**Comment by riturajjain2000** [comment] 2021-04-04 07:31
Sorry for the delay everyone, I was a little busy with my college placement procedures.
I am unable to reproduce the error. Is there any other way to reproduce it?

**Comment by linl33** [comment] 2021-04-04 13:41
It might be an OS dependent thing, could you try on Android 8.1?
Note that on step 5, do not rotate the screen back to its original orientation.

**Comment by riturajjain2000** [comment] 2021-04-04 14:34
> It might be an OS dependent thing, could you try on Android 8.1?
> Note that on step 5, do not rotate the screen back to its original orientation.

Ok will do that .
Will update if I face any problem

**Comment by riturajjain2000** [comment] 2021-04-17 06:59
Can this be closed as I have fixed the issue 😃

**Closed** 2021-04-17 09:09 UTC
Labels: Services, bug
